   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.10 (r5363) -  9 Sep 2014 09:53
   !
   !  Differentiation of cross_product_3d in forward (tangent) mode (with options noISIZE i4 dr8 r8):
   !   variations   of useful results: cross
   !   with respect to varying inputs: cross v1 v2
   ! ====================================================================
   ! File: vectorUtils.f90
   ! Author: C.A.(Sandy) Mader
   ! Date Started: July 14, 2014
   ! Date Modified:
   SUBROUTINE CROSS_PRODUCT_3D_D(v1, v1b, v2, v2b, cross, crossb)
   USE CONSTANTS
   IMPLICIT NONE
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v1, v2
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v1b, v2b
   REAL(kind=realtype), DIMENSION(3), INTENT(OUT) :: cross
   REAL(kind=realtype), DIMENSION(3), INTENT(OUT) :: crossb
   crossb(1) = v1b(2)*v2(3) + v1(2)*v2b(3) - v1b(3)*v2(2) - v1(3)*v2b(2)
   cross(1) = v1(2)*v2(3) - v1(3)*v2(2)
   crossb(2) = v1b(3)*v2(1) + v1(3)*v2b(1) - v1b(1)*v2(3) - v1(1)*v2b(3)
   cross(2) = v1(3)*v2(1) - v1(1)*v2(3)
   crossb(3) = v1b(1)*v2(2) + v1(1)*v2b(2) - v1b(2)*v2(1) - v1(2)*v2b(1)
   cross(3) = v1(1)*v2(2) - v1(2)*v2(1)
   END SUBROUTINE CROSS_PRODUCT_3D_D
