   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.10 (r5363) -  9 Sep 2014 09:53
   !
   !  Differentiation of getmag in forward (tangent) mode (with options noISIZE i4 dr8 r8):
   !   variations   of useful results: mag
   !   with respect to varying inputs: v
   SUBROUTINE GETMAG_D(v, vb, mag, magb)
   USE CONSTANTS
   IMPLICIT NONE
   ! Subroutine Variables
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: vb
   REAL(kind=realtype), INTENT(OUT) :: mag
   REAL(kind=realtype), INTENT(OUT) :: magb
   INTRINSIC SQRT
   REAL(kind=realtype) :: arg1
   REAL(kind=realtype) :: arg1b
   arg1b = 2*v(1)*vb(1) + 2*v(2)*vb(2) + 2*v(3)*vb(3)
   arg1 = v(1)**2 + v(2)**2 + v(3)**2 + 1e-30
   IF (arg1 .EQ. 0.0_8) THEN
   magb = 0.0_8
   ELSE
   magb = arg1b/(2.0*SQRT(arg1))
   END IF
   mag = SQRT(arg1)
   END SUBROUTINE GETMAG_D
