   !        Generated by TAPENADE     (INRIA, Ecuador team)
   !  Tapenade 3.16 (develop) - 22 Aug 2023 15:51
   !
   !  Differentiation of getrotationmatrix3d in forward (tangent) mode (with options noISIZE i4 dr8 r8):
   !   variations   of useful results: mi
   !   with respect to varying inputs: v2
   SUBROUTINE GETROTATIONMATRIX3D_D(v1, v2, v2b, mi, mib)
   USE PRECISION
   USE CONSTANTS
   IMPLICIT NONE
   ! Subroutine Variables
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v1, v2
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v2b
   REAL(kind=realtype), DIMENSION(3, 3), INTENT(OUT) :: mi
   REAL(kind=realtype), DIMENSION(3, 3), INTENT(OUT) :: mib
   ! Local Variables
   REAL(kind=realtype), DIMENSION(3) :: a
   REAL(kind=realtype), DIMENSION(3) :: ab
   REAL(kind=realtype) :: magv1, magv2, s, dot, denom2
   REAL(kind=realtype) :: magv2b, sb, dotb, denom2b
   REAL(kind=realtype), DIMENSION(3, 3) :: p, c
   REAL(kind=realtype), DIMENSION(3, 3) :: pb, cb
   REAL(kind=realtype), PARAMETER :: dtol=1.0e-10
   REAL(kind=realtype), DIMENSION(3) :: v1b
   ! Rotation taking the direction of v1 to the direction of v2, in a
   ! smooth branch-free form.  With theta the angle between v1 and v2,
   ! a = v1 x v2 and s = |v1||v2|, the two axis-angle pieces of the
   ! Rodrigues formula reduce EXACTLY (for 0 <= theta < pi) to
   !     sin(theta) * Ahat        = skew(a) / s
   !     (1-cos(theta)) * Ahat^2  = skew(a)^2 / (s^2 + s*(v1.v2))
   ! so no normalized axis, no acos and no angle are ever formed.  The
   ! axis-angle version this replaces needed an axisMag < tol branch at
   ! theta = 0, and BOTH AD derivatives (_b and _d) of that branch were
   ! identically zero while the true derivative there is finite: every
   ! surface node of an UNDEFORMED mesh evaluates at exactly theta = 0,
   ! so warpDeriv/warpDerivFwd silently dropped the entire rotation
   ! contribution when linearized at the baseline configuration.  This
   ! form has a removable limit at theta = 0 (a = 0 makes the rotation
   ! terms vanish smoothly) and differentiates correctly there by
   ! construction.  Only theta -> pi (anti-parallel normals, a folded
   ! surface) is guarded, where the rotation genuinely is not unique.
   CALL GETMAG(v1, magv1)
   CALL GETMAG_D(v2, v2b, magv2, magv2b)
   ab = 0.0_8
   v1b = 0.0_8
   CALL CROSS_PRODUCT_3D_D(v1, v1b, v2, v2b, a, ab)
   sb = magv1*magv2b
   s = magv1*magv2
   dotb = v1(1)*v2b(1) + v1(2)*v2b(2) + v1(3)*v2b(3)
   dot = v1(1)*v2(1) + v1(2)*v2(2) + v1(3)*v2(3)
   denom2b = (2*s+dot)*sb + s*dotb
   denom2 = s*s + s*dot
   IF (denom2 .LT. dtol*s*s) THEN
   denom2b = dtol*2*s*sb
   denom2 = dtol*s*s
   END IF
   ! P = skew(a)
   p(1, 1) = zero
   pb = 0.0_8
   pb(1, 2) = -ab(3)
   p(1, 2) = -a(3)
   pb(1, 3) = ab(2)
   p(1, 3) = a(2)
   pb(2, 1) = ab(3)
   p(2, 1) = a(3)
   pb(2, 2) = 0.0_8
   p(2, 2) = zero
   pb(2, 3) = -ab(1)
   p(2, 3) = -a(1)
   pb(3, 1) = -ab(2)
   p(3, 1) = -a(2)
   pb(3, 2) = ab(1)
   p(3, 2) = a(1)
   pb(3, 3) = 0.0_8
   p(3, 3) = zero
   ! C = P*P = a a^T - (a.a) I
   cb = 0.0_8
   cb(1, 1) = -(2*a(2)*ab(2)) - 2*a(3)*ab(3)
   c(1, 1) = -(a(2)*a(2)) - a(3)*a(3)
   cb(1, 2) = a(2)*ab(1) + a(1)*ab(2)
   c(1, 2) = a(1)*a(2)
   cb(1, 3) = a(3)*ab(1) + a(1)*ab(3)
   c(1, 3) = a(1)*a(3)
   cb(2, 1) = a(2)*ab(1) + a(1)*ab(2)
   c(2, 1) = a(1)*a(2)
   cb(2, 2) = -(2*a(1)*ab(1)) - 2*a(3)*ab(3)
   c(2, 2) = -(a(1)*a(1)) - a(3)*a(3)
   cb(2, 3) = a(3)*ab(2) + a(2)*ab(3)
   c(2, 3) = a(2)*a(3)
   cb(3, 1) = a(3)*ab(1) + a(1)*ab(3)
   c(3, 1) = a(1)*a(3)
   cb(3, 2) = a(3)*ab(2) + a(2)*ab(3)
   c(3, 2) = a(2)*a(3)
   cb(3, 3) = -(2*a(1)*ab(1)) - 2*a(2)*ab(2)
   c(3, 3) = -(a(1)*a(1)) - a(2)*a(2)
   mi = zero
   mi(1, 1) = one
   mi(2, 2) = one
   mi(3, 3) = one
   mib = (pb-p*sb/s)/s + (cb-c*denom2b/denom2)/denom2
   mi = mi + p/s + c/denom2
   END SUBROUTINE GETROTATIONMATRIX3D_D
      !  Differentiation of cross_product_3d in forward (tangent) mode (with options noISIZE i4 dr8 r8):
   !   variations   of useful results: cross
   !   with respect to varying inputs: cross v1 v2
   ! ====================================================================
   ! File: vectorUtils.f90
   ! Author: C.A.(Sandy) Mader
   ! Date Started: July 14, 2014
   ! Date Modified:
   SUBROUTINE CROSS_PRODUCT_3D_D(v1, v1b, v2, v2b, cross, crossb)
   USE CONSTANTS
   IMPLICIT NONE
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v1, v2
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v1b, v2b
   REAL(kind=realtype), DIMENSION(3), INTENT(OUT) :: cross
   REAL(kind=realtype), DIMENSION(3), INTENT(OUT) :: crossb
   crossb(1) = v2(3)*v1b(2) + v1(2)*v2b(3) - v2(2)*v1b(3) - v1(3)*v2b(2)
   cross(1) = v1(2)*v2(3) - v1(3)*v2(2)
   crossb(2) = v2(1)*v1b(3) + v1(3)*v2b(1) - v2(3)*v1b(1) - v1(1)*v2b(3)
   cross(2) = v1(3)*v2(1) - v1(1)*v2(3)
   crossb(3) = v2(2)*v1b(1) + v1(1)*v2b(2) - v2(1)*v1b(2) - v1(2)*v2b(1)
   cross(3) = v1(1)*v2(2) - v1(2)*v2(1)
   END SUBROUTINE CROSS_PRODUCT_3D_D
      !  Differentiation of getmag in forward (tangent) mode (with options noISIZE i4 dr8 r8):
   !   variations   of useful results: mag
   !   with respect to varying inputs: v
   SUBROUTINE GETMAG_D(v, vb, mag, magb)
   USE CONSTANTS
   IMPLICIT NONE
   ! Subroutine Variables
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: vb
   REAL(kind=realtype), INTENT(OUT) :: mag
   REAL(kind=realtype), INTENT(OUT) :: magb
   INTRINSIC SQRT
   REAL(kind=realtype) :: arg1
   REAL(kind=realtype) :: arg1b
   REAL(kind=realtype) :: temp
   arg1b = 2*v(1)*vb(1) + 2*v(2)*vb(2) + 2*v(3)*vb(3)
   arg1 = v(1)**2 + v(2)**2 + v(3)**2 + 1e-30
   temp = SQRT(arg1)
   IF (arg1 .EQ. 0.0_8) THEN
   magb = 0.0_8
   ELSE
   magb = arg1b/(2.0*temp)
   END IF
   mag = temp
   END SUBROUTINE GETMAG_D
   