   !        Generated by TAPENADE     (INRIA, Ecuador team)
   !  Tapenade 3.16 (develop) - 22 Aug 2023 15:51
   !
   !  Differentiation of getrotationmatrix3d in reverse (adjoint) mode (with options noISIZE i4 dr8 r8):
   !   gradient     of useful results: v2 mi
   !   with respect to varying inputs: v2
   SUBROUTINE GETROTATIONMATRIX3D_B(v1, v2, v2b, mi, mib)
   USE PRECISION
   USE CONSTANTS
   IMPLICIT NONE
   ! Subroutine Variables
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v1, v2
   REAL(kind=realtype), DIMENSION(3) :: v2b
   REAL(kind=realtype), DIMENSION(3, 3) :: mi
   REAL(kind=realtype), DIMENSION(3, 3) :: mib
   ! Local Variables
   REAL(kind=realtype), DIMENSION(3) :: a
   REAL(kind=realtype), DIMENSION(3) :: ab
   REAL(kind=realtype) :: magv1, magv2, s, dot, denom2
   REAL(kind=realtype) :: magv2b, sb, dotb, denom2b
   REAL(kind=realtype), DIMENSION(3, 3) :: p, c
   REAL(kind=realtype), DIMENSION(3, 3) :: pb, cb
   REAL(kind=realtype), PARAMETER :: dtol=1.0e-10
   REAL(kind=realtype), DIMENSION(3) :: v1b
   INTEGER :: branch
   ! Rotation taking the direction of v1 to the direction of v2, in a
   ! smooth branch-free form.  With theta the angle between v1 and v2,
   ! a = v1 x v2 and s = |v1||v2|, the two axis-angle pieces of the
   ! Rodrigues formula reduce EXACTLY (for 0 <= theta < pi) to
   !     sin(theta) * Ahat        = skew(a) / s
   !     (1-cos(theta)) * Ahat^2  = skew(a)^2 / (s^2 + s*(v1.v2))
   ! so no normalized axis, no acos and no angle are ever formed.  The
   ! axis-angle version this replaces needed an axisMag < tol branch at
   ! theta = 0, and BOTH AD derivatives (_b and _d) of that branch were
   ! identically zero while the true derivative there is finite: every
   ! surface node of an UNDEFORMED mesh evaluates at exactly theta = 0,
   ! so warpDeriv/warpDerivFwd silently dropped the entire rotation
   ! contribution when linearized at the baseline configuration.  This
   ! form has a removable limit at theta = 0 (a = 0 makes the rotation
   ! terms vanish smoothly) and differentiates correctly there by
   ! construction.  Only theta -> pi (anti-parallel normals, a folded
   ! surface) is guarded, where the rotation genuinely is not unique.
   CALL GETMAG(v1, magv1)
   CALL GETMAG(v2, magv2)
   CALL CROSS_PRODUCT_3D(v1, v2, a)
   s = magv1*magv2
   dot = v1(1)*v2(1) + v1(2)*v2(2) + v1(3)*v2(3)
   denom2 = s*s + s*dot
   IF (denom2 .LT. dtol*s*s) THEN
   denom2 = dtol*s*s
   CALL PUSHCONTROL1B(0)
   ELSE
   CALL PUSHCONTROL1B(1)
   END IF
   ! P = skew(a)
   p(1, 1) = zero
   p(1, 2) = -a(3)
   p(1, 3) = a(2)
   p(2, 1) = a(3)
   p(2, 2) = zero
   p(2, 3) = -a(1)
   p(3, 1) = -a(2)
   p(3, 2) = a(1)
   p(3, 3) = zero
   ! C = P*P = a a^T - (a.a) I
   c(1, 1) = -(a(2)*a(2)) - a(3)*a(3)
   c(1, 2) = a(1)*a(2)
   c(1, 3) = a(1)*a(3)
   c(2, 1) = a(1)*a(2)
   c(2, 2) = -(a(1)*a(1)) - a(3)*a(3)
   c(2, 3) = a(2)*a(3)
   c(3, 1) = a(1)*a(3)
   c(3, 2) = a(2)*a(3)
   c(3, 3) = -(a(1)*a(1)) - a(2)*a(2)
   pb = 0.0_8
   cb = 0.0_8
   pb = mib/s
   sb = -(SUM(p*mib)/s**2)
   cb = mib/denom2
   denom2b = -(SUM(c*mib)/denom2**2)
   ab = 0.0_8
   ab(1) = ab(1) + a(3)*cb(3, 1) - 2*a(1)*cb(3, 3) + a(2)*cb(2, 1) - 2*a(&
   &   1)*cb(2, 2) + a(3)*cb(1, 3) + a(2)*cb(1, 2) + pb(3, 2) - pb(2, 3)
   ab(2) = ab(2) + a(3)*cb(3, 2) - 2*a(2)*cb(3, 3) + a(3)*cb(2, 3) + a(1)&
   &   *cb(2, 1) + a(1)*cb(1, 2) + pb(1, 3) - 2*a(2)*cb(1, 1) - pb(3, 1)
   cb(3, 3) = 0.0_8
   ab(3) = ab(3) + a(2)*cb(3, 2) + a(1)*cb(3, 1) + a(2)*cb(2, 3) + a(1)*&
   &   cb(1, 3) - 2*a(3)*cb(2, 2) + pb(2, 1) - 2*a(3)*cb(1, 1) - pb(1, 2)
   cb(3, 2) = 0.0_8
   cb(3, 1) = 0.0_8
   cb(2, 3) = 0.0_8
   cb(2, 2) = 0.0_8
   cb(2, 1) = 0.0_8
   cb(1, 3) = 0.0_8
   cb(1, 2) = 0.0_8
   pb(3, 3) = 0.0_8
   pb(3, 2) = 0.0_8
   pb(3, 1) = 0.0_8
   pb(2, 3) = 0.0_8
   pb(2, 2) = 0.0_8
   pb(2, 1) = 0.0_8
   pb(1, 3) = 0.0_8
   CALL POPCONTROL1B(branch)
   IF (branch .EQ. 0) THEN
   sb = sb + 2*s*dtol*denom2b
   denom2b = 0.0_8
   END IF
   sb = sb + (2*s+dot)*denom2b
   dotb = s*denom2b
   v2b(1) = v2b(1) + v1(1)*dotb
   v2b(2) = v2b(2) + v1(2)*dotb
   v2b(3) = v2b(3) + v1(3)*dotb
   magv2b = magv1*sb
   v1b = 0.0_8
   CALL CROSS_PRODUCT_3D_B(v1, v1b, v2, v2b, a, ab)
   CALL GETMAG_B(v2, v2b, magv2, magv2b)
   END SUBROUTINE GETROTATIONMATRIX3D_B
      !  Differentiation of cross_product_3d in reverse (adjoint) mode (with options noISIZE i4 dr8 r8):
   !   gradient     of useful results: cross v1 v2
   !   with respect to varying inputs: cross v1 v2
   ! ====================================================================
   ! File: vectorUtils.f90
   ! Author: C.A.(Sandy) Mader
   ! Date Started: July 14, 2014
   ! Date Modified:
   SUBROUTINE CROSS_PRODUCT_3D_B(v1, v1b, v2, v2b, cross, crossb)
   USE CONSTANTS
   IMPLICIT NONE
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v1, v2
   REAL(kind=realtype), DIMENSION(3) :: v1b, v2b
   REAL(kind=realtype), DIMENSION(3) :: cross
   REAL(kind=realtype), DIMENSION(3) :: crossb
   v1b(1) = v1b(1) + v2(2)*crossb(3) - v2(3)*crossb(2)
   v2b(2) = v2b(2) + v1(1)*crossb(3) - v1(3)*crossb(1)
   v1b(2) = v1b(2) + v2(3)*crossb(1) - v2(1)*crossb(3)
   v2b(1) = v2b(1) + v1(3)*crossb(2) - v1(2)*crossb(3)
   crossb(3) = 0.0_8
   v1b(3) = v1b(3) + v2(1)*crossb(2) - v2(2)*crossb(1)
   v2b(3) = v2b(3) + v1(2)*crossb(1) - v1(1)*crossb(2)
   crossb(2) = 0.0_8
   crossb(1) = 0.0_8
   END SUBROUTINE CROSS_PRODUCT_3D_B
      !  Differentiation of getmag in reverse (adjoint) mode (with options noISIZE i4 dr8 r8):
   !   gradient     of useful results: v mag
   !   with respect to varying inputs: v
   SUBROUTINE GETMAG_B(v, vb, mag, magb)
   USE CONSTANTS
   IMPLICIT NONE
   ! Subroutine Variables
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v
   REAL(kind=realtype), DIMENSION(3) :: vb
   REAL(kind=realtype) :: mag
   REAL(kind=realtype) :: magb
   INTRINSIC SQRT
   REAL(kind=realtype) :: tempb
   IF (v(1)**2 + v(2)**2 + v(3)**2 + 1e-30 .EQ. 0.0_8) THEN
   tempb = 0.0_8
   ELSE
   tempb = magb/(2.0*SQRT(v(1)**2+v(2)**2+v(3)**2+1e-30))
   END IF
   vb(1) = vb(1) + 2*v(1)*tempb
   vb(2) = vb(2) + 2*v(2)*tempb
   vb(3) = vb(3) + 2*v(3)*tempb
   END SUBROUTINE GETMAG_B
   