   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.10 (r5363) -  9 Sep 2014 09:53
   !
   !  Differentiation of getelementprops in reverse (adjoint) mode (with options noISIZE i4 dr8 r8):
   !   gradient     of useful results: area points normal
   !   with respect to varying inputs: points
   SUBROUTINE GETELEMENTPROPS_B(points, pointsb, npts, area, areab, normal&
   & , normalb)
   USE CONSTANTS
   IMPLICIT NONE
   INTEGER(kind=inttype), INTENT(IN) :: npts
   ! subroutine Variables
   REAL(kind=realtype), DIMENSION(3, npts), INTENT(IN) :: points
   REAL(kind=realtype), DIMENSION(3, npts) :: pointsb
   REAL(kind=realtype), DIMENSION(3) :: normal
   REAL(kind=realtype), DIMENSION(3) :: normalb
   REAL(kind=realtype) :: area
   REAL(kind=realtype) :: areab
   ! Local variables
   INTEGER(kind=inttype) :: i
   REAL(kind=realtype), DIMENSION(3, npts) :: radialvec
   REAL(kind=realtype), DIMENSION(3, npts) :: radialvecb
   REAL(kind=realtype), DIMENSION(3) :: center, cross
   REAL(kind=realtype), DIMENSION(3) :: centerb, crossb
   REAL(kind=realtype) :: crossnorm
   REAL(kind=realtype) :: crossnormb
   INTRINSIC SQRT
   REAL(kind=realtype), DIMENSION(3) :: tmp
   INTEGER :: branch
   REAL(kind=realtype) :: temp0
   REAL(kind=realtype) :: tempb0
   REAL(kind=realtype) :: tmpb(3)
   REAL(kind=realtype) :: tempb
   REAL(kind=realtype) :: temp
   ! Compute the element center:
   center(:) = zero
   DO i=1,npts
   center(:) = center(:) + points(:, i)
   END DO
   center = center/npts
   ! compute the vector from the center to each point defining the element
   DO i=1,npts
   radialvec(:, i) = points(:, i) - center
   END DO
   ! Now loop around element doing cross products to get directional area
   CALL PUSHREAL8ARRAY(normal, realtype*3/8)
   normal = zero
   DO i=1,npts
   IF (i .LT. npts) THEN
   CALL PUSHREAL8ARRAY(cross, realtype*3/8)
   CALL CROSS_PRODUCT_3D(radialvec(:, i), radialvec(:, i+1), cross&
   &                       )
   CALL PUSHCONTROL1B(0)
   ELSE
   CALL PUSHREAL8ARRAY(cross, realtype*3/8)
   CALL CROSS_PRODUCT_3D(radialvec(:, i), radialvec(:, 1), cross)
   CALL PUSHCONTROL1B(1)
   END IF
   CALL PUSHREAL8ARRAY(crossnorm, realtype/8)
   crossnorm = SQRT(cross(1)**2 + cross(2)**2 + cross(3)**2 + 1e-15)
   normal = normal + cross/crossnorm
   END DO
   temp = normal(1)**2 + normal(2)**2 + normal(3)**2
   temp0 = SQRT(temp)
   tmpb = normalb
   normalb = tmpb/temp0
   IF (temp .EQ. 0.0_8) THEN
   tempb0 = 0.0
   ELSE
   tempb0 = SUM(-(normal*tmpb/temp0))/(temp0**2*2.0)
   END IF
   normalb(1) = normalb(1) + 2*normal(1)*tempb0
   normalb(2) = normalb(2) + 2*normal(2)*tempb0
   normalb(3) = normalb(3) + 2*normal(3)*tempb0
   crossb = 0.0_8
   radialvecb = 0.0_8
   DO i=npts,1,-1
   crossb = crossb + normalb/crossnorm
   crossnormb = half*areab + SUM(-(cross*normalb/crossnorm))/crossnorm
   CALL POPREAL8ARRAY(crossnorm, realtype/8)
   IF (cross(1)**2 + cross(2)**2 + cross(3)**2 + 1e-15 .EQ. 0.0_8) THEN
   tempb = 0.0
   ELSE
   tempb = crossnormb/(2.0*SQRT(cross(1)**2+cross(2)**2+cross(3)**2+&
   &       1e-15))
   END IF
   crossb(1) = crossb(1) + 2*cross(1)*tempb
   crossb(2) = crossb(2) + 2*cross(2)*tempb
   crossb(3) = crossb(3) + 2*cross(3)*tempb
   CALL POPCONTROL1B(branch)
   IF (branch .EQ. 0) THEN
   CALL POPREAL8ARRAY(cross, realtype*3/8)
   CALL CROSS_PRODUCT_3D_B(radialvec(:, i), radialvecb(:, i), &
   &                       radialvec(:, i+1), radialvecb(:, i+1), cross, &
   &                       crossb)
   ELSE
   CALL POPREAL8ARRAY(cross, realtype*3/8)
   CALL CROSS_PRODUCT_3D_B(radialvec(:, i), radialvecb(:, i), &
   &                       radialvec(:, 1), radialvecb(:, 1), cross, crossb&
   &                      )
   END IF
   END DO
   CALL POPREAL8ARRAY(normal, realtype*3/8)
   centerb = 0.0_8
   DO i=npts,1,-1
   pointsb(:, i) = pointsb(:, i) + radialvecb(:, i)
   centerb = centerb - radialvecb(:, i)
   radialvecb(:, i) = 0.0_8
   END DO
   centerb = centerb/npts
   DO i=npts,1,-1
   pointsb(:, i) = pointsb(:, i) + centerb
   END DO
   END SUBROUTINE GETELEMENTPROPS_B
