   !        Generated by TAPENADE     (INRIA, Tropics team)
   !  Tapenade 3.7 (r4786) - 21 Feb 2013 15:53
   !
   !  Differentiation of getmag in reverse (adjoint) mode (with options noISIZE i4 dr8 r8):
   !   gradient     of useful results: v mag
   !   with respect to varying inputs: v
   SUBROUTINE GETMAG_B(v, vb, mag, magb)
   USE CONSTANTS
   IMPLICIT NONE
   ! Subroutine Variables
   REAL(kind=realtype), DIMENSION(3), INTENT(IN) :: v
   REAL(kind=realtype), DIMENSION(3) :: vb
   REAL(kind=realtype) :: mag
   REAL(kind=realtype) :: magb
   REAL(kind=realtype) :: tempb
   IF (v(1)**2 + v(2)**2 + v(3)**2 + 1e-30 .EQ. 0.0_8) THEN
   tempb = 0.0
   ELSE
   tempb = magb/(2.0*SQRT(v(1)**2+v(2)**2+v(3)**2+1e-30))
   END IF
   vb(1) = vb(1) + 2*v(1)*tempb
   vb(2) = vb(2) + 2*v(2)*tempb
   vb(3) = vb(3) + 2*v(3)*tempb
   END SUBROUTINE GETMAG_B
