!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.7 (r4786) - 21 Feb 2013 15:53
!
!  Differentiation of warpmeshexact in reverse (adjoint) mode (with options noISIZE i4 dr8 r8):
!   gradient     of useful results: *xvptr
!   with respect to varying inputs: *xvptr *xsptr
!   RW status of diff variables: *xvptr:in-out *xsptr:out
!   Plus diff mem management of: xvptr:in xsptr:in xu:in bi:in
!                normals:in mi:in
SUBROUTINE WARPMESHEXACT_B()
  USE GRIDINPUT
  USE COMMUNICATION
  USE GRIDDATA
  IMPLICIT NONE
  ! This is gateway function to the N^2 (exact) mesh warping
  ! algorithm. The input to this function is XsPtr a (flatted) 1D
  ! array of the surface coordinates and the ouput XvPtr a (flatted)
  ! 1D arary of the volume coordinates. This routine is AD-able by
  ! Tapendade in both forward and reverse modes.
  ! Working parameters
  REAL(kind=realtype) :: dist, ldefodist, wi, den
  REAL(kind=realtype), DIMENSION(3) :: r, rr, num, si
  REAL(kind=realtype), DIMENSION(3) :: numb
  INTEGER(kind=inttype) :: nvol, i, j
  REAL(kind=realtype) :: ldef, alphatobexp, oden
  REAL(kind=realtype) :: ldefodist3
  REAL(kind=realtype) :: timea, timeb
  INTRINSIC SIZE
  INTRINSIC SQRT
  ! Update the nodal properties
  ldef = ldef0*ldeffact
  alphatobexp = alpha**bexp
  nvol = SIZE(xvptr)/3
  bib = 0.0_8
  DO j=1,nvol
     r(1) = xv0ptr(3*j-2)
     r(2) = xv0ptr(3*j-1)
     r(3) = xv0ptr(3*j)
     den = zero
     DO i=1,nunique
        rr = r - xu0(:, i)
        dist = SQRT(rr(1)**2 + rr(2)**2 + rr(3)**2 + 1e-15)
        ldefodist = ldef/dist
        ldefodist3 = ldefodist**3
        CALL PUSHREAL8ARRAY(wi, realtype/8)
        wi = ai(i)*(ldefodist3+alphatobexp*ldefodist3*ldefodist*ldefodist)
        den = den + wi
     END DO
     numb = 0.0_8
     numb(3) = numb(3) + xvptrb(3*j)/den
     xvptrb(3*j) = 0.0_8
     numb(2) = numb(2) + xvptrb(3*j-1)/den
     xvptrb(3*j-1) = 0.0_8
     numb(1) = numb(1) + xvptrb(3*j-2)/den
     xvptrb(3*j-2) = 0.0_8

     DO i=nunique,1,-1
        bib(:, i) = bib(:, i) + wi*numb
        CALL POPREAL8ARRAY(wi, realtype/8)
     END DO
  END DO
  CALL COMPUTENODALPROPERTIES_B(.false.)
END SUBROUTINE WARPMESHEXACT_B
